### ISSUE TITLE
Use pytest to run benchmarks

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/benchmark#16]

**Comment by JoanFM** [comment]
May u elaborate on why is this desired?

**Comment by tadejsv** [comment]
I think we can simply use pytest to run the benchmarks. We will still implement saving results ourselves, but pytest can be used to
- create fixtures
- manage parameter matrices
- show us the progress of the benchmarks
- save us from writing entry scripts in each file

It should also be easy to adopt, we all know very well how pytest works already.

And to clarify, I am talking only about pytest, not pytest-benchmarks, or any other plugins.

**Comment by JoanFM** [comment]
Makes sense,

@maateen any drawback?

**Comment by tadejsv** [comment]
@JoanFM how would it invalidate the structure?

**Comment by JoanFM** [comment]
ah no, sorry I mistaked, it would just force us to call every function `test_` right? which makes sense because they are sort of tests.

I thought for a sec that pytest only inspects under test folder

**Comment by tadejsv** [comment]
I think even that might be configurable, I will check in detail later
https://docs.pytest.org/en/6.2.x/example/pythoncollection.html#changing-naming-conventions

**Comment by JoanFM** [comment]
I think it is okey to have this

**Comment by maateen** [comment]
@tadejsv Would you like to suggest this feature on a small scale in a branch? This might help: https://github.com/ionelmc/pytest-benchmark
